# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/Mark/Documents/GitHub/cibyl/tools/translator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/Mark/Documents/GitHub/cibyl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Mark/Documents/GitHub/cibyl/CMakeFiles /mnt/c/Users/Mark/Documents/GitHub/cibyl//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Mark/Documents/GitHub/cibyl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named xcibyl-translator

# Build rule for target.
xcibyl-translator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xcibyl-translator
.PHONY : xcibyl-translator

# fast build rule for target.
xcibyl-translator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/build
.PHONY : xcibyl-translator/fast

# target to build an object file
basicblock.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/basicblock.o
.PHONY : basicblock.o

# target to preprocess a source file
basicblock.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/basicblock.i
.PHONY : basicblock.i

# target to generate assembly for a file
basicblock.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/basicblock.s
.PHONY : basicblock.s

# target to build an object file
builtins.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/builtins.o
.PHONY : builtins.o

# target to preprocess a source file
builtins.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/builtins.i
.PHONY : builtins.i

# target to generate assembly for a file
builtins.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/builtins.s
.PHONY : builtins.s

# target to build an object file
calltablemethod.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/calltablemethod.o
.PHONY : calltablemethod.o

# target to preprocess a source file
calltablemethod.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/calltablemethod.i
.PHONY : calltablemethod.i

# target to generate assembly for a file
calltablemethod.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/calltablemethod.s
.PHONY : calltablemethod.s

# target to build an object file
codeblock.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/codeblock.o
.PHONY : codeblock.o

# target to preprocess a source file
codeblock.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/codeblock.i
.PHONY : codeblock.i

# target to generate assembly for a file
codeblock.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/codeblock.s
.PHONY : codeblock.s

# target to build an object file
controller.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/controller.o
.PHONY : controller.o

# target to preprocess a source file
controller.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/controller.i
.PHONY : controller.i

# target to generate assembly for a file
controller.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/controller.s
.PHONY : controller.s

# target to build an object file
elf.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/elf.o
.PHONY : elf.o

# target to preprocess a source file
elf.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/elf.i
.PHONY : elf.i

# target to generate assembly for a file
elf.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/elf.s
.PHONY : elf.s

# target to build an object file
emit.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/emit.o
.PHONY : emit.o

# target to preprocess a source file
emit.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/emit.i
.PHONY : emit.i

# target to generate assembly for a file
emit.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/emit.s
.PHONY : emit.s

# target to build an object file
external/elfutils/dwarf_abbrev_hash.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_abbrev_hash.o
.PHONY : external/elfutils/dwarf_abbrev_hash.o

# target to preprocess a source file
external/elfutils/dwarf_abbrev_hash.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_abbrev_hash.i
.PHONY : external/elfutils/dwarf_abbrev_hash.i

# target to generate assembly for a file
external/elfutils/dwarf_abbrev_hash.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_abbrev_hash.s
.PHONY : external/elfutils/dwarf_abbrev_hash.s

# target to build an object file
external/elfutils/dwarf_attr.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_attr.o
.PHONY : external/elfutils/dwarf_attr.o

# target to preprocess a source file
external/elfutils/dwarf_attr.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_attr.i
.PHONY : external/elfutils/dwarf_attr.i

# target to generate assembly for a file
external/elfutils/dwarf_attr.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_attr.s
.PHONY : external/elfutils/dwarf_attr.s

# target to build an object file
external/elfutils/dwarf_attr_integrate.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_attr_integrate.o
.PHONY : external/elfutils/dwarf_attr_integrate.o

# target to preprocess a source file
external/elfutils/dwarf_attr_integrate.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_attr_integrate.i
.PHONY : external/elfutils/dwarf_attr_integrate.i

# target to generate assembly for a file
external/elfutils/dwarf_attr_integrate.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_attr_integrate.s
.PHONY : external/elfutils/dwarf_attr_integrate.s

# target to build an object file
external/elfutils/dwarf_begin_elf.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_begin_elf.o
.PHONY : external/elfutils/dwarf_begin_elf.o

# target to preprocess a source file
external/elfutils/dwarf_begin_elf.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_begin_elf.i
.PHONY : external/elfutils/dwarf_begin_elf.i

# target to generate assembly for a file
external/elfutils/dwarf_begin_elf.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_begin_elf.s
.PHONY : external/elfutils/dwarf_begin_elf.s

# target to build an object file
external/elfutils/dwarf_child.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_child.o
.PHONY : external/elfutils/dwarf_child.o

# target to preprocess a source file
external/elfutils/dwarf_child.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_child.i
.PHONY : external/elfutils/dwarf_child.i

# target to generate assembly for a file
external/elfutils/dwarf_child.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_child.s
.PHONY : external/elfutils/dwarf_child.s

# target to build an object file
external/elfutils/dwarf_end.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_end.o
.PHONY : external/elfutils/dwarf_end.o

# target to preprocess a source file
external/elfutils/dwarf_end.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_end.i
.PHONY : external/elfutils/dwarf_end.i

# target to generate assembly for a file
external/elfutils/dwarf_end.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_end.s
.PHONY : external/elfutils/dwarf_end.s

# target to build an object file
external/elfutils/dwarf_error.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_error.o
.PHONY : external/elfutils/dwarf_error.o

# target to preprocess a source file
external/elfutils/dwarf_error.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_error.i
.PHONY : external/elfutils/dwarf_error.i

# target to generate assembly for a file
external/elfutils/dwarf_error.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_error.s
.PHONY : external/elfutils/dwarf_error.s

# target to build an object file
external/elfutils/dwarf_formaddr.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_formaddr.o
.PHONY : external/elfutils/dwarf_formaddr.o

# target to preprocess a source file
external/elfutils/dwarf_formaddr.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_formaddr.i
.PHONY : external/elfutils/dwarf_formaddr.i

# target to generate assembly for a file
external/elfutils/dwarf_formaddr.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_formaddr.s
.PHONY : external/elfutils/dwarf_formaddr.s

# target to build an object file
external/elfutils/dwarf_formref.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_formref.o
.PHONY : external/elfutils/dwarf_formref.o

# target to preprocess a source file
external/elfutils/dwarf_formref.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_formref.i
.PHONY : external/elfutils/dwarf_formref.i

# target to generate assembly for a file
external/elfutils/dwarf_formref.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_formref.s
.PHONY : external/elfutils/dwarf_formref.s

# target to build an object file
external/elfutils/dwarf_formref_die.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_formref_die.o
.PHONY : external/elfutils/dwarf_formref_die.o

# target to preprocess a source file
external/elfutils/dwarf_formref_die.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_formref_die.i
.PHONY : external/elfutils/dwarf_formref_die.i

# target to generate assembly for a file
external/elfutils/dwarf_formref_die.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_formref_die.s
.PHONY : external/elfutils/dwarf_formref_die.s

# target to build an object file
external/elfutils/dwarf_formudata.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_formudata.o
.PHONY : external/elfutils/dwarf_formudata.o

# target to preprocess a source file
external/elfutils/dwarf_formudata.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_formudata.i
.PHONY : external/elfutils/dwarf_formudata.i

# target to generate assembly for a file
external/elfutils/dwarf_formudata.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_formudata.s
.PHONY : external/elfutils/dwarf_formudata.s

# target to build an object file
external/elfutils/dwarf_getabbrev.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_getabbrev.o
.PHONY : external/elfutils/dwarf_getabbrev.o

# target to preprocess a source file
external/elfutils/dwarf_getabbrev.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_getabbrev.i
.PHONY : external/elfutils/dwarf_getabbrev.i

# target to generate assembly for a file
external/elfutils/dwarf_getabbrev.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_getabbrev.s
.PHONY : external/elfutils/dwarf_getabbrev.s

# target to build an object file
external/elfutils/dwarf_hasattr.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_hasattr.o
.PHONY : external/elfutils/dwarf_hasattr.o

# target to preprocess a source file
external/elfutils/dwarf_hasattr.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_hasattr.i
.PHONY : external/elfutils/dwarf_hasattr.i

# target to generate assembly for a file
external/elfutils/dwarf_hasattr.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_hasattr.s
.PHONY : external/elfutils/dwarf_hasattr.s

# target to build an object file
external/elfutils/dwarf_hasattr_integrate.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_hasattr_integrate.o
.PHONY : external/elfutils/dwarf_hasattr_integrate.o

# target to preprocess a source file
external/elfutils/dwarf_hasattr_integrate.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_hasattr_integrate.i
.PHONY : external/elfutils/dwarf_hasattr_integrate.i

# target to generate assembly for a file
external/elfutils/dwarf_hasattr_integrate.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_hasattr_integrate.s
.PHONY : external/elfutils/dwarf_hasattr_integrate.s

# target to build an object file
external/elfutils/dwarf_lowpc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_lowpc.o
.PHONY : external/elfutils/dwarf_lowpc.o

# target to preprocess a source file
external/elfutils/dwarf_lowpc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_lowpc.i
.PHONY : external/elfutils/dwarf_lowpc.i

# target to generate assembly for a file
external/elfutils/dwarf_lowpc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_lowpc.s
.PHONY : external/elfutils/dwarf_lowpc.s

# target to build an object file
external/elfutils/dwarf_nextcu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_nextcu.o
.PHONY : external/elfutils/dwarf_nextcu.o

# target to preprocess a source file
external/elfutils/dwarf_nextcu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_nextcu.i
.PHONY : external/elfutils/dwarf_nextcu.i

# target to generate assembly for a file
external/elfutils/dwarf_nextcu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_nextcu.s
.PHONY : external/elfutils/dwarf_nextcu.s

# target to build an object file
external/elfutils/dwarf_offdie.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_offdie.o
.PHONY : external/elfutils/dwarf_offdie.o

# target to preprocess a source file
external/elfutils/dwarf_offdie.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_offdie.i
.PHONY : external/elfutils/dwarf_offdie.i

# target to generate assembly for a file
external/elfutils/dwarf_offdie.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_offdie.s
.PHONY : external/elfutils/dwarf_offdie.s

# target to build an object file
external/elfutils/dwarf_siblingof.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_siblingof.o
.PHONY : external/elfutils/dwarf_siblingof.o

# target to preprocess a source file
external/elfutils/dwarf_siblingof.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_siblingof.i
.PHONY : external/elfutils/dwarf_siblingof.i

# target to generate assembly for a file
external/elfutils/dwarf_siblingof.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_siblingof.s
.PHONY : external/elfutils/dwarf_siblingof.s

# target to build an object file
external/elfutils/dwarf_sig8_hash.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_sig8_hash.o
.PHONY : external/elfutils/dwarf_sig8_hash.o

# target to preprocess a source file
external/elfutils/dwarf_sig8_hash.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_sig8_hash.i
.PHONY : external/elfutils/dwarf_sig8_hash.i

# target to generate assembly for a file
external/elfutils/dwarf_sig8_hash.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_sig8_hash.s
.PHONY : external/elfutils/dwarf_sig8_hash.s

# target to build an object file
external/elfutils/dwarf_tag.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_tag.o
.PHONY : external/elfutils/dwarf_tag.o

# target to preprocess a source file
external/elfutils/dwarf_tag.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_tag.i
.PHONY : external/elfutils/dwarf_tag.i

# target to generate assembly for a file
external/elfutils/dwarf_tag.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/dwarf_tag.s
.PHONY : external/elfutils/dwarf_tag.s

# target to build an object file
external/elfutils/frame-cache.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/frame-cache.o
.PHONY : external/elfutils/frame-cache.o

# target to preprocess a source file
external/elfutils/frame-cache.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/frame-cache.i
.PHONY : external/elfutils/frame-cache.i

# target to generate assembly for a file
external/elfutils/frame-cache.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/frame-cache.s
.PHONY : external/elfutils/frame-cache.s

# target to build an object file
external/elfutils/libdw_alloc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/libdw_alloc.o
.PHONY : external/elfutils/libdw_alloc.o

# target to preprocess a source file
external/elfutils/libdw_alloc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/libdw_alloc.i
.PHONY : external/elfutils/libdw_alloc.i

# target to generate assembly for a file
external/elfutils/libdw_alloc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/libdw_alloc.s
.PHONY : external/elfutils/libdw_alloc.s

# target to build an object file
external/elfutils/libdw_findcu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/libdw_findcu.o
.PHONY : external/elfutils/libdw_findcu.o

# target to preprocess a source file
external/elfutils/libdw_findcu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/libdw_findcu.i
.PHONY : external/elfutils/libdw_findcu.i

# target to generate assembly for a file
external/elfutils/libdw_findcu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/libdw_findcu.s
.PHONY : external/elfutils/libdw_findcu.s

# target to build an object file
external/elfutils/libdw_form.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/libdw_form.o
.PHONY : external/elfutils/libdw_form.o

# target to preprocess a source file
external/elfutils/libdw_form.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/libdw_form.i
.PHONY : external/elfutils/libdw_form.i

# target to generate assembly for a file
external/elfutils/libdw_form.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/external/elfutils/libdw_form.s
.PHONY : external/elfutils/libdw_form.s

# target to build an object file
function.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/function.o
.PHONY : function.o

# target to preprocess a source file
function.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/function.i
.PHONY : function.i

# target to generate assembly for a file
function.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/function.s
.PHONY : function.s

# target to build an object file
functioncolocation.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/functioncolocation.o
.PHONY : functioncolocation.o

# target to preprocess a source file
functioncolocation.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/functioncolocation.i
.PHONY : functioncolocation.i

# target to generate assembly for a file
functioncolocation.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/functioncolocation.s
.PHONY : functioncolocation.s

# target to build an object file
instruction.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/instruction.o
.PHONY : instruction.o

# target to preprocess a source file
instruction.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/instruction.i
.PHONY : instruction.i

# target to generate assembly for a file
instruction.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/instruction.s
.PHONY : instruction.s

# target to build an object file
javaclass.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/javaclass.o
.PHONY : javaclass.o

# target to preprocess a source file
javaclass.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/javaclass.i
.PHONY : javaclass.i

# target to generate assembly for a file
javaclass.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/javaclass.s
.PHONY : javaclass.s

# target to build an object file
javamethod.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/javamethod.o
.PHONY : javamethod.o

# target to preprocess a source file
javamethod.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/javamethod.i
.PHONY : javamethod.i

# target to generate assembly for a file
javamethod.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/javamethod.s
.PHONY : javamethod.s

# target to build an object file
mips-dwarf.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/mips-dwarf.o
.PHONY : mips-dwarf.o

# target to preprocess a source file
mips-dwarf.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/mips-dwarf.i
.PHONY : mips-dwarf.i

# target to generate assembly for a file
mips-dwarf.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/mips-dwarf.s
.PHONY : mips-dwarf.s

# target to build an object file
mips.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/mips.o
.PHONY : mips.o

# target to preprocess a source file
mips.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/mips.i
.PHONY : mips.i

# target to generate assembly for a file
mips.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/mips.s
.PHONY : mips.s

# target to build an object file
registerallocator.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/registerallocator.o
.PHONY : registerallocator.o

# target to preprocess a source file
registerallocator.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/registerallocator.i
.PHONY : registerallocator.i

# target to generate assembly for a file
registerallocator.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/registerallocator.s
.PHONY : registerallocator.s

# target to build an object file
string-instruction.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/string-instruction.o
.PHONY : string-instruction.o

# target to preprocess a source file
string-instruction.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/string-instruction.i
.PHONY : string-instruction.i

# target to generate assembly for a file
string-instruction.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/string-instruction.s
.PHONY : string-instruction.s

# target to build an object file
syscall-wrappers.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/syscall-wrappers.o
.PHONY : syscall-wrappers.o

# target to preprocess a source file
syscall-wrappers.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/syscall-wrappers.i
.PHONY : syscall-wrappers.i

# target to generate assembly for a file
syscall-wrappers.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/syscall-wrappers.s
.PHONY : syscall-wrappers.s

# target to build an object file
utils.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/utils.o
.PHONY : utils.o

# target to preprocess a source file
utils.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/utils.i
.PHONY : utils.i

# target to generate assembly for a file
utils.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcibyl-translator.dir/build.make CMakeFiles/xcibyl-translator.dir/utils.s
.PHONY : utils.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... xcibyl-translator"
	@echo "... basicblock.o"
	@echo "... basicblock.i"
	@echo "... basicblock.s"
	@echo "... builtins.o"
	@echo "... builtins.i"
	@echo "... builtins.s"
	@echo "... calltablemethod.o"
	@echo "... calltablemethod.i"
	@echo "... calltablemethod.s"
	@echo "... codeblock.o"
	@echo "... codeblock.i"
	@echo "... codeblock.s"
	@echo "... controller.o"
	@echo "... controller.i"
	@echo "... controller.s"
	@echo "... elf.o"
	@echo "... elf.i"
	@echo "... elf.s"
	@echo "... emit.o"
	@echo "... emit.i"
	@echo "... emit.s"
	@echo "... external/elfutils/dwarf_abbrev_hash.o"
	@echo "... external/elfutils/dwarf_abbrev_hash.i"
	@echo "... external/elfutils/dwarf_abbrev_hash.s"
	@echo "... external/elfutils/dwarf_attr.o"
	@echo "... external/elfutils/dwarf_attr.i"
	@echo "... external/elfutils/dwarf_attr.s"
	@echo "... external/elfutils/dwarf_attr_integrate.o"
	@echo "... external/elfutils/dwarf_attr_integrate.i"
	@echo "... external/elfutils/dwarf_attr_integrate.s"
	@echo "... external/elfutils/dwarf_begin_elf.o"
	@echo "... external/elfutils/dwarf_begin_elf.i"
	@echo "... external/elfutils/dwarf_begin_elf.s"
	@echo "... external/elfutils/dwarf_child.o"
	@echo "... external/elfutils/dwarf_child.i"
	@echo "... external/elfutils/dwarf_child.s"
	@echo "... external/elfutils/dwarf_end.o"
	@echo "... external/elfutils/dwarf_end.i"
	@echo "... external/elfutils/dwarf_end.s"
	@echo "... external/elfutils/dwarf_error.o"
	@echo "... external/elfutils/dwarf_error.i"
	@echo "... external/elfutils/dwarf_error.s"
	@echo "... external/elfutils/dwarf_formaddr.o"
	@echo "... external/elfutils/dwarf_formaddr.i"
	@echo "... external/elfutils/dwarf_formaddr.s"
	@echo "... external/elfutils/dwarf_formref.o"
	@echo "... external/elfutils/dwarf_formref.i"
	@echo "... external/elfutils/dwarf_formref.s"
	@echo "... external/elfutils/dwarf_formref_die.o"
	@echo "... external/elfutils/dwarf_formref_die.i"
	@echo "... external/elfutils/dwarf_formref_die.s"
	@echo "... external/elfutils/dwarf_formudata.o"
	@echo "... external/elfutils/dwarf_formudata.i"
	@echo "... external/elfutils/dwarf_formudata.s"
	@echo "... external/elfutils/dwarf_getabbrev.o"
	@echo "... external/elfutils/dwarf_getabbrev.i"
	@echo "... external/elfutils/dwarf_getabbrev.s"
	@echo "... external/elfutils/dwarf_hasattr.o"
	@echo "... external/elfutils/dwarf_hasattr.i"
	@echo "... external/elfutils/dwarf_hasattr.s"
	@echo "... external/elfutils/dwarf_hasattr_integrate.o"
	@echo "... external/elfutils/dwarf_hasattr_integrate.i"
	@echo "... external/elfutils/dwarf_hasattr_integrate.s"
	@echo "... external/elfutils/dwarf_lowpc.o"
	@echo "... external/elfutils/dwarf_lowpc.i"
	@echo "... external/elfutils/dwarf_lowpc.s"
	@echo "... external/elfutils/dwarf_nextcu.o"
	@echo "... external/elfutils/dwarf_nextcu.i"
	@echo "... external/elfutils/dwarf_nextcu.s"
	@echo "... external/elfutils/dwarf_offdie.o"
	@echo "... external/elfutils/dwarf_offdie.i"
	@echo "... external/elfutils/dwarf_offdie.s"
	@echo "... external/elfutils/dwarf_siblingof.o"
	@echo "... external/elfutils/dwarf_siblingof.i"
	@echo "... external/elfutils/dwarf_siblingof.s"
	@echo "... external/elfutils/dwarf_sig8_hash.o"
	@echo "... external/elfutils/dwarf_sig8_hash.i"
	@echo "... external/elfutils/dwarf_sig8_hash.s"
	@echo "... external/elfutils/dwarf_tag.o"
	@echo "... external/elfutils/dwarf_tag.i"
	@echo "... external/elfutils/dwarf_tag.s"
	@echo "... external/elfutils/frame-cache.o"
	@echo "... external/elfutils/frame-cache.i"
	@echo "... external/elfutils/frame-cache.s"
	@echo "... external/elfutils/libdw_alloc.o"
	@echo "... external/elfutils/libdw_alloc.i"
	@echo "... external/elfutils/libdw_alloc.s"
	@echo "... external/elfutils/libdw_findcu.o"
	@echo "... external/elfutils/libdw_findcu.i"
	@echo "... external/elfutils/libdw_findcu.s"
	@echo "... external/elfutils/libdw_form.o"
	@echo "... external/elfutils/libdw_form.i"
	@echo "... external/elfutils/libdw_form.s"
	@echo "... function.o"
	@echo "... function.i"
	@echo "... function.s"
	@echo "... functioncolocation.o"
	@echo "... functioncolocation.i"
	@echo "... functioncolocation.s"
	@echo "... instruction.o"
	@echo "... instruction.i"
	@echo "... instruction.s"
	@echo "... javaclass.o"
	@echo "... javaclass.i"
	@echo "... javaclass.s"
	@echo "... javamethod.o"
	@echo "... javamethod.i"
	@echo "... javamethod.s"
	@echo "... mips-dwarf.o"
	@echo "... mips-dwarf.i"
	@echo "... mips-dwarf.s"
	@echo "... mips.o"
	@echo "... mips.i"
	@echo "... mips.s"
	@echo "... registerallocator.o"
	@echo "... registerallocator.i"
	@echo "... registerallocator.s"
	@echo "... string-instruction.o"
	@echo "... string-instruction.i"
	@echo "... string-instruction.s"
	@echo "... syscall-wrappers.o"
	@echo "... syscall-wrappers.i"
	@echo "... syscall-wrappers.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

