# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Compiler
      run: |
          sudo apt-get install help2man
          sudo apt-get install libtool-bin
          sudo apt-get install libelf-dev
#
#          cd toolchain
#          make #
#          export PATH=$PATH:/home/runner/work/cibyl/cibyl/mips-cibyl-elf/bin

    - name: Setup environment
      run: |
          cd toolchain
          pwd
          wget https://github.com/DeviousMalcontent/cibyl/releases/download/v7/mips-cibyl-elf.tar.bz2
          tar -xjf mips-cibyl-elf.tar.bz2
          dir
          export PATH=$PATH:/home/runner/work/cibyl/cibyl/toolchain/mips-cibyl-elf/bin
          cd /home/runner/work/cibyl/cibyl/toolchain/mips-cibyl-elf
          dir
          alias mips-cibyl-elf-gcc=/home/runner/work/cibyl/cibyl/toolchain/mips-cibyl-elf/bin/mips-cibyl-elf-gcc
          which mips-cibyl-elf-gcc
#          sudo rsync -a /home/runner/work/cibyl/cibyl/toolchain/mips-cibyl-elf/ /cibyl/

    - name: Update python lib
      run: |
          sudo apt install 2to3
          pip install reindent
          pip install config

          2to3 /home/runner/work/cibyl/cibyl/tools/cibyl-config -W
          2to3 /home/runner/work/cibyl/cibyl/tools/cibyl-gdbserver -W
          2to3 /home/runner/work/cibyl/cibyl/tools/cibyl-generate-c-header -W
          2to3 /home/runner/work/cibyl/cibyl/tools/cibyl-generate-cibar -W
          2to3 /home/runner/work/cibyl/cibyl/tools/cibyl-generate-java-wrappers -W
          2to3 /home/runner/work/cibyl/cibyl/tools/cibyl-generate-syscall-db -W
          2to3 /home/runner/work/cibyl/cibyl/tools/cibyl-mips2java -W
          2to3 /home/runner/work/cibyl/cibyl/tools/cibyl-peephole-optimize -W
          2to3 --output-dir=/home/runner/work/cibyl/cibyl/tools/python -W -n /home/runner/work/cibyl/cibyl/tools/python
          
          reindent -n /home/runner/work/cibyl/cibyl/tools/cibyl-config
          reindent -n /home/runner/work/cibyl/cibyl/tools/cibyl-generate-c-header
          reindent -n /home/runner/work/cibyl/cibyl/tools/cibyl-generate-cibar
          reindent -n /home/runner/work/cibyl/cibyl/tools/cibyl-generate-java-wrappers
          reindent -n /home/runner/work/cibyl/cibyl/tools/cibyl-generate-syscall-db
          reindent -n /home/runner/work/cibyl/cibyl/tools/cibyl-mips2java
          reindent -n /home/runner/work/cibyl/cibyl/tools/cibyl-peephole-optimize
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/BinaryTranslation/Mips/__init__.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/BinaryTranslation/Mips/instruction.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/BinaryTranslation/Mips/javamethod.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/BinaryTranslation/Mips/mips.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/BinaryTranslation/Mips/optimizer.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/BinaryTranslation/Optimization/Builtins/__init__.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/BinaryTranslation/Optimization/Builtins/base.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/BinaryTranslation/Optimization/Builtins/builtins.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/BinaryTranslation/Optimization/Builtins/exceptions.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/BinaryTranslation/Optimization/Builtins/softfloat.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/BinaryTranslation/Optimization/Mips/
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/BinaryTranslation/Optimization/Mips/__init__.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/BinaryTranslation/Optimization/Mips/mult.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/BinaryTranslation/Optimization/__init__.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/BinaryTranslation/__init__.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/BinaryTranslation/basicblock.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/BinaryTranslation/bytecode.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/BinaryTranslation/codeblock.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/BinaryTranslation/function.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/BinaryTranslation/javaclass.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/BinaryTranslation/labelmanager.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/BinaryTranslation/profile.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/BinaryTranslation/register.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/BinaryTranslation/translator.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/CompiledHelpers/__init__.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/CompiledHelpers/helpers.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/GdbServer/__init__.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/GdbServer/gdbmips.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/GdbServer/gdbserver.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/GdbServer/jdb.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/GdbServer/packets.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/PeepholeOptimizer/__init__.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/PeepholeOptimizer/classes.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/PeepholeOptimizer/emit.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/PeepholeOptimizer/parse.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/PeepholeOptimizer/template.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/PeepholeOptimizer/templates/__init__.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/PeepholeOptimizer/templates/const_and_inc.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/PeepholeOptimizer/templates/const_and_pop.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/PeepholeOptimizer/templates/const_store_aload.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/PeepholeOptimizer/templates/double_pop.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/PeepholeOptimizer/templates/double_stores.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/PeepholeOptimizer/templates/dup_pop.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/PeepholeOptimizer/templates/getstatic_v1_pop.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/PeepholeOptimizer/templates/goto_next_line.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/PeepholeOptimizer/templates/jal_arguments.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/PeepholeOptimizer/templates/jal_return.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/PeepholeOptimizer/templates/memory-getstatic.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/PeepholeOptimizer/templates/push_store_inc.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/PeepholeOptimizer/templates/putstatic_getstatic.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/PeepholeOptimizer/templates/unused_label.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/__init__.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/function.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/__init__.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/config.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/Cibyl/elf.py
          reindent -n /home/runner/work/cibyl/cibyl/tools/python/which.py

          sed -i '19s#.*#FUNCTION_NAME="([A-Z,a-z,0-9,_,\\\\(,\\\\)]+)"#' /home/runner/work/cibyl/cibyl/tools/python/Cibyl/PeepholeOptimizer/parse.py
          sed -i '25s#.*#comment = re.compile("[ ,\\t]*;([A-Z,a-z,0-9,_,\\\\(,\\\\), ]+):")#' //home/runner/work/cibyl/cibyl/tools/python/Cibyl/PeepholeOptimizer/parse.py
          sed -i '45s#.*#instruction = re.compile("\\t([A-Z,a-z,0-9,_,\\\\(,\\\\), ]+)")#' /home/runner/work/cibyl/cibyl/tools/python/Cibyl/PeepholeOptimizer/parse.py

          sed -i '178s#.*#                for line in readPreprocessedFile("/home/cibyl/mips-cibyl-elf/sys-root/usr/share/syscalls/java/imports", self.defines):#' /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py

          sed -i '15s#.*#from Cibyl.BinaryTranslation.Mips.instruction import Instruction#' /home/runner/work/cibyl/cibyl/tools/python/Cibyl/BinaryTranslation/function.py
          sed -i '16s#.*#from Cibyl.BinaryTranslation.Mips import mips#' /home/runner/work/cibyl/cibyl/tools/python/Cibyl/BinaryTranslation/function.py

          sed -i "301iblank" /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i '301s#.*#        data = struct.pack("P", 0x11b1c1d1)#' /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i "302iblank" /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i '302s#.*#        hex_str = data.hex()#' /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i '303s#.*#        of.write(hex_str)#' /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py

          sed -i "304iblank" /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i '304s#.*#        data2 = struct.pack("P", len(self.dirs))#' /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i "305iblank" /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i '305s#.*#        dir_str = data2.hex()#' /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i '306s#.*#        of.write(dir_str)#' /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py

          sed -i "307iblank" /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i '307s#.*#        data3 = struct.pack("P", len(self.syscallSets))#' /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i "308iblank" /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i '308s#.*#        syscall_str = data3.hex()#' /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i '309s#.*#        of.write(syscall_str)#' /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          
          sed -i "310iblank" /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i '310s#.*#        data4 = struct.pack("P", len(out))#' /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i "311iblank" /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i '311s#.*#        out_str = data3.hex()#' /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i '312s#.*#        of.write(out_str)#' /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          
          sed -i "313iblank" /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i '313s#.*#        data4 = (struct.pack("P", arg_offs))#' /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i "314iblank" /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i '314s#.*#        arg_offs_str = data4.hex()#' /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i '315s#.*#        of.write(arg_offs_str)#' /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          
          sed -i "316iblank" /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i '316s#.*#        data4 = struct.pack("P", strtab_offs)#' /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i "317iblank" /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i '317s#.*#        strtab_offs_str = data4.hex()#' /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i '318s#.*#        of.write(strtab_offs_str)#' /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py

          sed -i "323iblank" /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i '323s#.*#        data5 = struct.pack("P", offs)#' /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i "324iblank" /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i '324s#.*#        offs1_str = data5.hex()#' /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i '325s#.*#        of.write(offs1_str)#' /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py

          sed -i "330iblank" /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i '330s#.*#        data6 = struct.pack("P", offs)#' /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i "331iblank" /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i '331s#.*#        offs2_str = data6.hex()#' /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py
          sed -i '332s#.*#        of.write(offs2_str)#' /home/runner/work/cibyl/cibyl/tools/python/Cibyl/SyscallHandling/syscallgenerator.py

    - name: Build translator and the cibyl libraries
      run: |
          cd /home/runner/work/cibyl/cibyl/
          cd build
          cmake ../
          make && make install
          echo -- here --
          pwd
          dir
          echo -- done! --

    - name: Upload Builds
      uses: actions/upload-artifact@v4
      with:
        name: cibyl for linux
        path: /home/runner/work/cibyl/cibyl/toolchain/mips-cibyl-elf.tar.bz2

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
          tag_name: v${{ github.run_number }}
          release_name: 'Release v${{ github.run_number }}'
          body: 'Cibyl CI Release'
          draft: false
          prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: /home/runner/work/cibyl/cibyl/toolchain/mips-cibyl-elf.tar.bz2
          asset_name: mips-cibyl-elf.tar.bz2
          asset_content_type: application/x-bzip2
