#!/bin/bash
SCRIPT=$(readlink -f "$0")
P=$(dirname "$SCRIPT")

echo "mips-cibyl-elf-g++"

$P/mips-cibyl-elf-g++.real -G0 -DCIBYL=1 -ggdb -msoft-float -fno-optimize-sibling-calls -Wa,--no-warn -mips1 -mno-check-zero-division -fno-pic -mno-abicalls -nostdlib -nostartfiles -nodefaultlibs -fno-exceptions -fno-rtti --sysroot="$P/../mips-cibyl-elf/sys-root" "-I${P}/../mips-cibyl-elf/sys-root/usr/include/" "-L${P}/../mips-cibyl-elf/sys-root/lib/" $*
